In [ ]:
import numpy 

In [ ]:
print(numpy.__version__)

1.21.6


In [ ]:
import numpy as np 
l = [1,2,3,4,5,6,7,8,9,10]
narray = np.array(l)
narray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
narray +5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
narray*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
narray-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [ ]:
import numpy as np 
l = ["Apple","Ball"]
narray = np.array(l)
narray

array(['Apple', 'Ball'], dtype='<U5')

In [ ]:
import numpy as np
l = ["Apple","Ball"]
k = ["Cat","Dog"]
narray1 = np.array(l)
narray2 = np.array(k) # numpy arrays only adds numerical values not string

narray1+narray2

UFuncTypeError: ignored

In [ ]:
import numpy as np
l = [1,2]
k = [3,4]
narray1 = np.array(l)
narray2 = np.array(k)

narray1+narray2

array([4, 6])

In [ ]:
l = [1,2,3,4,5]
narray = np.array(l)
narray.shape

(5,)

In [ ]:
l = [[1,2,3,4,5],[6,7,8,9,10]]
narray = np.array(l)
narray.shape


(2, 5)

In [ ]:
l = [[[1,2],[2,3]],
     [[4,5],[6,7]]]
narray = np.array(l)
narray.shape


(2, 2, 2)

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
l = [[1,2,3],[4,5,6]]
l_a = np.array(l)
l_a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
l = [[1,2,3],
     [4,5,6]]
l_a = np.array(l)
l_a.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
np.random.rand(5,5)

array([[0.45806955, 0.84573068, 0.41020975, 0.02034839, 0.61047784],
       [0.24109887, 0.50161319, 0.73411423, 0.89276654, 0.72260223],
       [0.12505481, 0.00860063, 0.07970645, 0.53816099, 0.73302861],
       [0.30451124, 0.62562783, 0.8560856 , 0.73602861, 0.65633118],
       [0.92215081, 0.47223377, 0.9759041 , 0.28126681, 0.65817272]])

In [ ]:
print(np.random.randint(0, 10, size=[5,5]))


[[8 6 5 7 2]
 [5 9 4 2 5]
 [9 4 8 4 7]
 [7 3 0 1 1]
 [3 6 8 0 2]]


In [ ]:
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))  

['i' 'o' 'o' 'a' 'e' 'u' 'i' 'o' 'u' 'a']


In [ ]:
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10,p=[0.3, .1, 0.1, 0.4, 0.1]))  


['a' 'o' 'o' 'o' 'e' 'i' 'o' 'o' 'o' 'e']


In [ ]:
a= [234,345,34,46,35,56,343,567,234]
n_a = np.array(a)
np.mean(n_a)

210.44444444444446

In [ ]:
a = [234,345,34,46,35,56,343,567,234]
n_a = np.array(a)
np.std(n_a)

175.34924586291027

In [ ]:
a = [1,2,3,1,2,3,1,2,3,1,1,1]
n_a = np.array(a)
np.std(n_a)

0.82915619758885